# Generated by Django 2.0.7 on 2018-09-02 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tactics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tactic',
            options={'ordering': ('-created',)},
        ),
    ]
