# Generated by Django 2.0.7 on 2018-09-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactics', '0002_auto_20180902_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='tactic',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
