# Generated by Django 2.0.7 on 2018-09-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactics', '0003_tactic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tactic',
            name='image',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
