# Generated by Django 2.0.7 on 2018-12-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='bill_frequency',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('WEEK', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('BESPOKE', 'Bespoke')], default='MO', max_length=10),
        ),
    ]
