# Generated by Django 2.0.7 on 2018-09-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offering',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
    ]
