# Generated by Django 2.0.7 on 2019-04-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20190421_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='catslug'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='catslug'),
        ),
    ]
