# Generated by Django 2.0.7 on 2018-12-11 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
    ]
