# Generated by Django 2.0.7 on 2019-04-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20190421_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
